//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paho
{
    using System;
    using System.Collections.Generic;
    
    public partial class Area
    {
        public Area()
        {
            this.CaseGEOs = new HashSet<CaseGEO>();
            this.Institutions = new HashSet<Institution>();
            this.States = new HashSet<State>();
        }
    
        public int ID { get; set; }
        public int CountryID { get; set; }
        public string Name { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual ICollection<CaseGEO> CaseGEOs { get; set; }
        public virtual ICollection<Institution> Institutions { get; set; }
        public virtual ICollection<State> States { get; set; }
    }
}
