//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paho
{
    using System;
    using System.Collections.Generic;
    
    public partial class CaseLabTest
    {
        public int ID { get; set; }
        public int FluCaseID { get; set; }
        public Nullable<int> VirusTypeID { get; set; }
        public int TestType { get; set; }
        public string TestResultID { get; set; }
        public Nullable<System.DateTime> TestDate { get; set; }
        public Nullable<System.DateTime> TestEndDate { get; set; }
        public Nullable<int> UserID { get; set; }
        public System.DateTime InsertDate { get; set; }
        public System.DateTime LastUpdate { get; set; }
    
        public virtual FluCase FluCase { get; set; }
        public virtual TestResult TestResult { get; set; }
        public virtual VirusType VirusType { get; set; }
    }
}
