//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paho
{
    using System;
    using System.Collections.Generic;
    
    public partial class CaseGEO
    {
        public int ID { get; set; }
        public Nullable<int> CountryID { get; set; }
        public Nullable<int> AreaID { get; set; }
        public Nullable<int> StateID { get; set; }
        public Nullable<int> LocalID { get; set; }
        public Nullable<int> NeighborhoodID { get; set; }
        public Nullable<int> UrbanRural { get; set; }
        public string Address { get; set; }
    
        public virtual Area Area { get; set; }
        public virtual Country Country { get; set; }
        public virtual FluCase FluCase { get; set; }
        public virtual Local Local { get; set; }
        public virtual Neighborhood Neighborhood { get; set; }
        public virtual State State { get; set; }
    }
}
