//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paho
{
    using System;
    using System.Collections.Generic;
    
    public partial class CaseSummaryDetail
    {
        public int Id { get; set; }
        public int CaseSummaryId { get; set; }
        public int AgeGroup { get; set; }
        public int HospFem { get; set; }
        public int HospMaso { get; set; }
        public int HospST { get; set; }
        public int UCIFem { get; set; }
        public int UCIMaso { get; set; }
        public int UCIST { get; set; }
        public int DefFem { get; set; }
        public int DefMaso { get; set; }
        public int DefST { get; set; }
    
        public virtual CaseSummary CaseSummary { get; set; }
    }
}
