//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paho
{
    using System;
    using System.Collections.Generic;
    
    public partial class CaseHospital
    {
        public int ID { get; set; }
        public string CHNum { get; set; }
        public Nullable<System.DateTime> FeverDate { get; set; }
        public Nullable<int> FeverEW { get; set; }
        public string Antiviral { get; set; }
        public Nullable<System.DateTime> AStartDate { get; set; }
        public Nullable<System.DateTime> HospAmDate { get; set; }
        public Nullable<int> HospEW { get; set; }
        public Nullable<System.DateTime> HospExDate { get; set; }
        public Nullable<System.DateTime> ICUAmDate { get; set; }
        public Nullable<int> ICUEW { get; set; }
        public Nullable<System.DateTime> ICUExDate { get; set; }
        public string Destin { get; set; }
        public Nullable<bool> IsSample { get; set; }
        public Nullable<System.DateTime> SampleDate { get; set; }
        public string SampleType { get; set; }
        public Nullable<System.DateTime> ShipDate { get; set; }
        public Nullable<long> LabID { get; set; }
    
        public virtual FluCase FluCase { get; set; }
        public virtual Institution Institution { get; set; }
    }
}
