//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paho
{
    using System;
    using System.Collections.Generic;
    
    public partial class CaseRisk
    {
        public int ID { get; set; }
        public Nullable<int> Vaccin { get; set; }
        public int RiskFactors { get; set; }
        public Nullable<bool> HDisease { get; set; }
        public Nullable<bool> Diabetes { get; set; }
        public Nullable<bool> Neuro { get; set; }
        public Nullable<bool> Asthma { get; set; }
        public Nullable<bool> Pulmonary { get; set; }
        public Nullable<bool> Liver { get; set; }
        public Nullable<bool> Renal { get; set; }
        public Nullable<bool> Immunsupp { get; set; }
        public Nullable<int> Pregnant { get; set; }
        public Nullable<bool> Pperium { get; set; }
        public Nullable<int> Trimester { get; set; }
        public Nullable<bool> Smoking { get; set; }
        public Nullable<bool> Alcohol { get; set; }
        public Nullable<bool> DownSyn { get; set; }
        public Nullable<int> Obesity { get; set; }
        public string OtherRisk { get; set; }
    
        public virtual FluCase FluCase { get; set; }
    }
}
