//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paho
{
    using System;
    using System.Collections.Generic;
    
    public partial class CaseLab
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> RecDate { get; set; }
        public bool Processed { get; set; }
        public string NoProRen { get; set; }
        public Nullable<System.DateTime> EndLabDate { get; set; }
        public string FResult { get; set; }
        public string Comments { get; set; }
    
        public virtual FluCase FluCase { get; set; }
    }
}
