//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paho
{
    using System;
    using System.Collections.Generic;
    
    public partial class CaseSummary
    {
        public CaseSummary()
        {
            this.CaseSummaryDetails = new HashSet<CaseSummaryDetail>();
        }
    
        public int Id { get; set; }
        public int HosiptalId { get; set; }
        public System.DateTime StartDateOfWeek { get; set; }
        public Nullable<int> UserID { get; set; }
        public System.DateTime InsertDate { get; set; }
        public System.DateTime LastUpdate { get; set; }
    
        public virtual ICollection<CaseSummaryDetail> CaseSummaryDetails { get; set; }
    }
}
