//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paho
{
    using System;
    using System.Collections.Generic;
    
    public partial class Country
    {
        public Country()
        {
            this.Areas = new HashSet<Area>();
            this.CaseGEOs = new HashSet<CaseGEO>();
            this.Institutions = new HashSet<Institution>();
        }
    
        public int ID { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public bool Active { get; set; }
    
        public virtual ICollection<Area> Areas { get; set; }
        public virtual ICollection<CaseGEO> CaseGEOs { get; set; }
        public virtual ICollection<Institution> Institutions { get; set; }
    }
}
