//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paho
{
    using System;
    using System.Collections.Generic;
    
    public partial class Institution
    {
        public Institution()
        {
            this.AspNetUsers = new HashSet<AspNetUser>();
            this.CaseHospitals = new HashSet<CaseHospital>();
            this.FluCases = new HashSet<FluCase>();
        }
    
        public long ID { get; set; }
        public Nullable<int> CountryID { get; set; }
        public Nullable<int> AreaID { get; set; }
        public string FullName { get; set; }
        public string Name { get; set; }
        public int AccessLevel { get; set; }
        public Nullable<long> InstID { get; set; }
        public int InstitutionType { get; set; }
    
        public virtual Area Area { get; set; }
        public virtual ICollection<AspNetUser> AspNetUsers { get; set; }
        public virtual ICollection<CaseHospital> CaseHospitals { get; set; }
        public virtual Country Country { get; set; }
        public virtual ICollection<FluCase> FluCases { get; set; }
    }
}
