//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paho
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PahoFluEntities1 : DbContext
    {
        public PahoFluEntities1()
            : base("name=PahoFluEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<Area> Areas { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<CaseGEO> CaseGEOs { get; set; }
        public virtual DbSet<CaseHospital> CaseHospitals { get; set; }
        public virtual DbSet<CaseLab> CaseLabs { get; set; }
        public virtual DbSet<CaseLabTest> CaseLabTests { get; set; }
        public virtual DbSet<CaseRisk> CaseRisks { get; set; }
        public virtual DbSet<CaseSummary> CaseSummaries { get; set; }
        public virtual DbSet<CaseSummaryDetail> CaseSummaryDetails { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<FluCase> FluCases { get; set; }
        public virtual DbSet<Institution> Institutions { get; set; }
        public virtual DbSet<Local> Locals { get; set; }
        public virtual DbSet<Neighborhood> Neighborhoods { get; set; }
        public virtual DbSet<State> States { get; set; }
        public virtual DbSet<TestResult> TestResults { get; set; }
        public virtual DbSet<VirusType> VirusTypes { get; set; }
    }
}
