//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paho
{
    using System;
    using System.Collections.Generic;
    
    public partial class State
    {
        public State()
        {
            this.CaseGEOs = new HashSet<CaseGEO>();
            this.Locals = new HashSet<Local>();
            this.Neighborhoods = new HashSet<Neighborhood>();
        }
    
        public int ID { get; set; }
        public int AreaID { get; set; }
        public string Name { get; set; }
    
        public virtual Area Area { get; set; }
        public virtual ICollection<CaseGEO> CaseGEOs { get; set; }
        public virtual ICollection<Local> Locals { get; set; }
        public virtual ICollection<Neighborhood> Neighborhoods { get; set; }
    }
}
