//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSConsume.WSPaCr {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://wscr.pahoflu.com/webservices/", ConfigurationName="WSPaCr.WSBDSoap")]
    public interface WSBDSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento cKey del espacio de nombres http://wscr.pahoflu.com/webservices/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://wscr.pahoflu.com/webservices/GetDaPI", ReplyAction="*")]
        WSConsume.WSPaCr.GetDaPIResponse GetDaPI(WSConsume.WSPaCr.GetDaPIRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wscr.pahoflu.com/webservices/GetDaPI", ReplyAction="*")]
        System.Threading.Tasks.Task<WSConsume.WSPaCr.GetDaPIResponse> GetDaPIAsync(WSConsume.WSPaCr.GetDaPIRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDaPIRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDaPI", Namespace="http://wscr.pahoflu.com/webservices/", Order=0)]
        public WSConsume.WSPaCr.GetDaPIRequestBody Body;
        
        public GetDaPIRequest() {
        }
        
        public GetDaPIRequest(WSConsume.WSPaCr.GetDaPIRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://wscr.pahoflu.com/webservices/")]
    public partial class GetDaPIRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int serverSQL;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string cKey;
        
        public GetDaPIRequestBody() {
        }
        
        public GetDaPIRequestBody(int serverSQL, string cKey) {
            this.serverSQL = serverSQL;
            this.cKey = cKey;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDaPIResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDaPIResponse", Namespace="http://wscr.pahoflu.com/webservices/", Order=0)]
        public WSConsume.WSPaCr.GetDaPIResponseBody Body;
        
        public GetDaPIResponse() {
        }
        
        public GetDaPIResponse(WSConsume.WSPaCr.GetDaPIResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://wscr.pahoflu.com/webservices/")]
    public partial class GetDaPIResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetDaPIResult;
        
        public GetDaPIResponseBody() {
        }
        
        public GetDaPIResponseBody(string GetDaPIResult) {
            this.GetDaPIResult = GetDaPIResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WSBDSoapChannel : WSConsume.WSPaCr.WSBDSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSBDSoapClient : System.ServiceModel.ClientBase<WSConsume.WSPaCr.WSBDSoap>, WSConsume.WSPaCr.WSBDSoap {
        
        public WSBDSoapClient() {
        }
        
        public WSBDSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WSBDSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSBDSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSBDSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WSConsume.WSPaCr.GetDaPIResponse WSConsume.WSPaCr.WSBDSoap.GetDaPI(WSConsume.WSPaCr.GetDaPIRequest request) {
            return base.Channel.GetDaPI(request);
        }
        
        public string GetDaPI(int serverSQL, string cKey) {
            WSConsume.WSPaCr.GetDaPIRequest inValue = new WSConsume.WSPaCr.GetDaPIRequest();
            inValue.Body = new WSConsume.WSPaCr.GetDaPIRequestBody();
            inValue.Body.serverSQL = serverSQL;
            inValue.Body.cKey = cKey;
            WSConsume.WSPaCr.GetDaPIResponse retVal = ((WSConsume.WSPaCr.WSBDSoap)(this)).GetDaPI(inValue);
            return retVal.Body.GetDaPIResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WSConsume.WSPaCr.GetDaPIResponse> WSConsume.WSPaCr.WSBDSoap.GetDaPIAsync(WSConsume.WSPaCr.GetDaPIRequest request) {
            return base.Channel.GetDaPIAsync(request);
        }
        
        public System.Threading.Tasks.Task<WSConsume.WSPaCr.GetDaPIResponse> GetDaPIAsync(int serverSQL, string cKey) {
            WSConsume.WSPaCr.GetDaPIRequest inValue = new WSConsume.WSPaCr.GetDaPIRequest();
            inValue.Body = new WSConsume.WSPaCr.GetDaPIRequestBody();
            inValue.Body.serverSQL = serverSQL;
            inValue.Body.cKey = cKey;
            return ((WSConsume.WSPaCr.WSBDSoap)(this)).GetDaPIAsync(inValue);
        }
    }
}
